<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kijidata [
  <!ELEMENT kijidata (entry+)>
  <!ELEMENT entry (day,label,title,content,url,image,alt)>
  <!ELEMENT day (#PCDATA)>
  <!ELEMENT label (#PCDATA)>
  <!ELEMENT title (#PCDATA)>  
  <!ELEMENT content (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  <!ELEMENT image (#PCDATA)>
  <!ELEMENT alt (#PCDATA)>
]>
<kijidata>
	<entry>
		<day>2022.09.30</day>
		<label>main</label>
		<title>細田議長と統一協会の関係/隠ぺいと無反省　国会で説明をできなければ辞任を</title>
		<content>日本共産党の志位和夫委員長は２９日、国会内で記者会見し、細田博之衆院議長が統一協会との関係を認める文書を発表したことについて問われ、「細田議長が統一協会の最大の広告塔の一人だったこ……</content>
		<url>https://www.jcp.or.jp/akahata/aik22/2022-09-30/2022093001_01_0.html</url>
		<image>images/sitetop/2022093001_01_0.jpg</image>
		<alt>写真</alt>
	</entry>
	<entry>
		<day>2021.07.16</day>
		<label>sub</label>
		<title>五輪　きっぱり中止に/新宿駅西口　共産党都議団が宣伝</title>
		<content></content>
		<url>https://nisihiramorinobu.github.io/n0626/</url>
		<image></image>
		<alt></alt>
	</entry>
	<entry>
		<day>2021.07.16</day>
		<label>sub</label>
		<title>国に上告断念を要請/「黒い雨」訴訟の原告ら</title>
		<content></content>
		<url>https://nisihiramorinobu.github.io/n0626/</url>
		<image></image>
		<alt></alt>
	</entry>
	<entry>
		<day>2021.07.16</day>
		<label>syutyo</label>
		<title>主張「黒い雨」再び勝訴/被爆者の苦しみ長引かせるな</title>
		<content></content>
		<url>https://nisihiramorinobu.github.io/n0626/</url>
		<image></image>
		<alt></alt>
	</entry>
	<entry>
		<day>2021.07.16</day>
		<label>tyoryu</label>
		<title>きょうの潮流</title>
		<content></content>
		<url>https://nisihiramorinobu.github.io/n0626/</url>
		<image></image>
		<alt></alt>
	</entry>
</kijidata>
